### ISSUE TITLE
Hot changes to VM attributes CPU/Memory not supported

### ISSUE THREAD

**Issue by rachappag** [IBM-tfproviders/vmware-vsphere#3]
Changes to number of CPUs and memory size always end up rebooting VM even though hot changes are allowed for the target VM.

**Comment by maheshd2** [comment]
Memory Hot Add Fix
------------------
The terraform vsphere provider has been changed to incorporte code for checking "memory hot add (MemoryHotAddEnabled)" flag before taking reboot decision.
- If "memory hot add (MemoryHotAddEnabled)" is set to true, then we do not reboot the VM.
- If "memory hot add (MemoryHotAddEnabled)" is set to false, then we reboot(power off-->apply changes-->power on) the VM.

And memory change (reduce) operation always need VM reboot(power off-->apply changes-->power on).

CPU Hot Plug Fix
----------------
The terraform vsphere provider has been changed to incorporte code for checking "cpu hot add (CpuHotAddEnabled)" flag and "cpu hot remove (CpuHotRemoveEnabled)" flag before taking reboot decision.
- If "cpu hot add (CpuHotAddEnabled)" and "cpu hot remove (CpuHotRemoveEnabled)" is set to true, then we do not reboot the VM.
- If "cpu hot add (CpuHotAddEnabled)" and "cpu hot remove (CpuHotRemoveEnabled)" is set to false, then we reboot(power off-->apply changes-->power on) the VM.

Fix Commit
------------
https://github.com/IBM-tfproviders/vmware-vsphere/commit/d9d68deb17403f9f75519e5d7e38a095adf1fbc1

**Comment by rachappag** [comment]
Fixes #11
